kind: Pod
apiVersion: v1
metadata: 
  name: multicontainer
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: alma
    image: almalinux:9
    command: ["sleep","2000"]