apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: course
      value: "kubernetes"
    - name: duration 
      value: "20hrs"