apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "64mi"
        cpu: "250m"
      limits:
        memory: "128mi"
        cpu: "500m"