kind: Pod
apiVersion: v1
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: nginx
        valueFrom:
          configMapKeyRef:
            name: 08-config-maps.yml
            key: course

   