apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    name: service-test
    environment: dev
    project: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      LoadBalancer: 32600 
