apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
    environment: dev
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      environment: dev
  # below is the pod definition
  template:
    metadata:
      labels:
         name: nginx
         environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        
          