kind: Replicaset
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: expense
    environment: dev
spec: # this is the replica definition
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
  template: # this is the pod definition
    metadata:
      name: nginx
      labels:
        project: expense
        environment: dev
    spec:
    containers:
      - name: nginx
        image: nginx    
        ports:
        - protocol: TCP
          containerPort: 80
