kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: expense
    environment: dev
spec: # this is the replica definition
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
  template: # this is the pod definition
    metadata:
      name: nginx
      labels:
        project: expense
        environment: dev
    spec:
     containers:
       - name: nginx-1
         image: nginx    
         ports:
         - protocol: TCP
           containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
      project: expense
      environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
